version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - mysql
    container_name: mta-hosting-web
    networks:
      - internal
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=mysql'

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./docker/.env
    ports:
      - 33066:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

# persisted storage
volumes:
  db-data: